### ISSUE TITLE
We should have a vote button on our homepage

### ISSUE THREAD

**Issue by s4y** [nko2/notmysegfault#22]
http://nodeknockout.com/iframe/fortnight-labs

http://blog.nodeknockout.com/post/9495034362/proprotip-customize-the-vote-ko-badge#disqus_thread

**Comment by afeld** [comment]
...and the GAME OVER page

**Comment by afeld** [comment]
added to the homepage by 18386f62981b864d5344e92b4d91ee2f10531717
